#
# Override for dev environment
#

services:
  app:
    build:
      target: base
      context: ./
      dockerfile: ./docker/app/Dockerfile # Relative to `context`
      args:
        DOCKER_BUILDKIT: 1
    restart: no
    pull_policy: build
    labels:
      - traefik.http.routers.cfe-${DOCKER_IMAGE_TAG:?}.rule=Host(`soliloan.localhost`)
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL:?}
      # File Watching Optimierung für Docker auf Mac
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
      - SMTP_FROM=noreply@soliloan.localhost
    volumes:
      - ./:/app:cached
      - /app/node_modules
    command: /bin/sh -c "pnpm install && pnpm prisma db push --accept-data-loss && pnpm prisma db seed && pnpm dev"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - backend_network